"""
Cy-Ares
------

A Cythonic Alternative to Pycares using cython instead of cffi 
for a performance increase.

"""

from .channel import (
    CYARES_SOCKET_BAD,
    QUERY_CLASS_ANY,
    QUERY_CLASS_CHAOS,
    QUERY_CLASS_HS,
    QUERY_CLASS_IN,
    QUERY_CLASS_NONE,
    QUERY_TYPE_A,
    QUERY_TYPE_AAAA,
    QUERY_TYPE_ANY,
    QUERY_TYPE_CAA,
    QUERY_TYPE_CNAME,
    QUERY_TYPE_MX,
    QUERY_TYPE_NAPTR,
    QUERY_TYPE_NS,
    QUERY_TYPE_PTR,
    QUERY_TYPE_SOA,
    QUERY_TYPE_SRV,
    QUERY_TYPE_TXT,
    Channel,
    cyares_threadsafety,
)
from .resulttypes import (
    AAAARecordData,
    AddrInfoCname,
    AddrInfoNode,
    AddrInfoResult,
    ARecordData,
    CAARecordData,
    CNAMERecordData,
    DNSRecord,
    DNSResult,
    HostResult,
    HTTPSRecordData,
    MXRecordData,
    NameInfoResult,
    NAPTRRecordData,
    NSRecordData,
    PTRRecordData,
    SOARecordData,
    SRVRecordData,
    TLSARecordData,
    TXTRecordData,
    URIRecordData,
)

__author__ = "Vizonex"
__version__ = "0.3.0"

__all__ = (
    "AAAARecordData",
    "ARecordData",
    "AddrInfoCname",
    "AddrInfoNode",
    "AddrInfoResult",
    "CAARecordData",
    "CNAMERecordData",
    "CYARES_SOCKET_BAD",
    "Channel",
    "DNSRecord",
    "DNSResult",
    "HTTPSRecordData",
    "HostResult",
    "MXRecordData",
    "NAPTRRecordData",
    "NSRecordData",
    "NameInfoResult",
    "PTRRecordData",
    "QUERY_CLASS_ANY",
    "QUERY_CLASS_CHAOS",
    "QUERY_CLASS_HS",
    "QUERY_CLASS_IN",
    "QUERY_CLASS_NONE",
    "QUERY_TYPE_A",
    "QUERY_TYPE_AAAA",
    "QUERY_TYPE_ANY",
    "QUERY_TYPE_CAA",
    "QUERY_TYPE_CNAME",
    "QUERY_TYPE_MX",
    "QUERY_TYPE_NAPTR",
    "QUERY_TYPE_NS",
    "QUERY_TYPE_PTR",
    "QUERY_TYPE_SOA",
    "QUERY_TYPE_SRV",
    "QUERY_TYPE_TXT",
    "SOARecordData",
    "SRVRecordData",
    "TLSARecordData",
    "TXTRecordData",
    "URIRecordData",
    "cyares_threadsafety",
)
