"""
error
-----

Contains compatability with pycares likewise
and allows for different forms of error tools
to be utilized.
"""

ARES_SUCCESS: int = ...
ARES_ENODATA: int = ...
ARES_EFORMERR: int = ...
ARES_ESERVFAIL: int = ...
ARES_ENOTFOUND: int = ...
ARES_ENOTIMP: int = ...
ARES_EREFUSED: int = ...
ARES_EBADQUERY: int = ...
ARES_EBADNAME: int = ...
ARES_EBADFAMILY: int = ...
ARES_EBADRESP: int = ...
ARES_ECONNREFUSED: int = ...
ARES_ETIMEOUT: int = ...
ARES_EOF: int = ...
ARES_EFILE: int = ...
ARES_ENOMEM: int = ...
ARES_EDESTRUCTION: int = ...
ARES_EBADSTR: int = ...
ARES_EBADFLAGS: int = ...
ARES_ENONAME: int = ...
ARES_EBADHINTS: int = ...
ARES_ENOTINITIALIZED: int = ...
ARES_ELOADIPHLPAPI: int = ...
ARES_EADDRGETNETWORKPARAMS: int = ...
ARES_ECANCELLED: int = ...
ARES_ESERVICE: int = ...
errorcode: dict[int, str] = ...

def strerror(status: int) -> str | bytes:
    """implemented for mirrored compatability with pycares"""
    ...

class AresError(Exception):
    """Raised when c-ares fails to do something"""

    status: int
    strerror: bytes
    name: bytes
    def __init__(self, status: int) -> None: ...
    def __str__(self) -> str: ...



